# Generated by Django 4.2.2 on 2023-06-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_dos_punto_cero', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
